version: 2
jobs:
  build:
    docker:
      - image: sonarqube:community


    environment:
      TEST_RESULTS: /tmp/test-results

    analyze:
    executor: machine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Code Analysis"
          command: |
            docker run --rm \
              -e SONAR_HOST_URL=$SONAR_HOST_URL \
              -e SONAR_LOGIN=$SONAR_LOGIN \
              -v "$(pwd):/usr/src" \
              sonarsource/sonar-scanner-cli \
                -Dsonar.projectKey=$CIRCLE_PROJECT_REPONAME \
                -Dsonar.pullrequest.key=$CIRCLE_PULL_REQUEST \
                -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \

workflows:
  version: 2
  build:
    jobs:
      - analyze:
          context: PR_BUILD
          requires:
              - build
          filters:
            branches:
              ignore:
                - master
                - homolog


