version: 2.1
orbs:
  sonarqube: clicklogiq/sonarqube@1.0.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - sonarqube/install-engine:
          engine_version: '4.2.0.1873' 

workflows:
  example-workflow:
    jobs:
      - example-job