version: 2.0

jobs:

  build:

    docker:



      - store_test_results:

          path: /tmp/test-results
  analyze:
    executor: machine
    steps:
      - checkout
      - run:
          name: "Code Analysis"
          command: |
            docker run --rm \
              -e SONAR_HOST_URL=$SONAR_HOST_URL \
              -e SONAR_LOGIN=$SONAR_LOGIN \
              -v "$(pwd):/usr/src" \
              sonarsource/sonar-scanner-cli