version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
       
 


  analyze:
    executor: machine
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Code Analysis"
          command: |
            docker run --rm \
              -e SONAR_HOST_URL=$SONAR_HOST_URL \
              -e SONAR_LOGIN=$SONAR_LOGIN \
              -v "$(pwd):/usr/src" \
              sonarsource/sonar-scanner-cli \
                -Dsonar.projectKey=$CIRCLE_PROJECT_REPONAME \
                -Dsonar.qualitygate.wait=true \
 