sonarqube:
  name: SonarQube
  runs-on: ubuntu-latest
  steps:
    - uses: philips-software/sonar-scanner-action@<version>
      with:
        token: ${{ secrets.SONARQUBE_TOKEN }}
        projectName: My Project Name
        projectKey: project.key.from.sonar.qube
        url: https://sonarqube.transfeera.com
        isCommunityEdition: true
